#ifndef ENGINE_CONSTANTS_H
#define ENGINE_CONSTANTS_H

#define N_TRACKS 3

#define SAMPLERATE 32000
#define SAMPLESPERBUF (SAMPLERATE * 120 / 1000)
#define NCHANNELS 2

#define OPUSSAMPLERATE 48000
#define OPUSSAMPLESPERFBUF (OPUSSAMPLERATE * 120 / 1000)

#endif // ENGINE_CONSTANTS_H